apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - universes.yaml
  - snapshot-julia-curve.yaml
  - snapshot-ust-par.yaml
  - dominos-julia.yaml
  - dominos-builtin.yaml
  - dominos-rates.yaml
