apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kbl-system
resources:
  - namespace.yaml
  - rbac.yaml
  - controller-deployment.yaml
  - tsdb-deployment.yaml
  - tsdb-service.yaml
