apiVersion: v1
kind: Service
metadata:
  name: kbl-tsdb
  namespace: kbl-system
  labels:
    app.kubernetes.io/name: kbl-tsdb
spec:
  selector:
    app.kubernetes.io/name: kbl-tsdb
  ports:
    - name: http
      port: 9090
      targetPort: http
