apiVersion: kbl.io/v1alpha1
kind: Workflow
metadata:
  name: finance-lab
  namespace: default
  labels:
    kbl.io/domain: finance
    kbl.io/lab: kind
spec:
  snapshotRef: julia-curve-2025-04-15
  dominoRefs:
    - builtin-identity
    - builtin-interpolate
    - builtin-risk-dv01
  execution:
    chain: [builtin-identity, builtin-interpolate, builtin-risk-dv01]
    deterministic: true
  provisioning:
    storePath: http://kbl-tsdb.kbl-system.svc.cluster.local:9090
    nodeLocal: true
  routing:
    universe: finance-local
    computeContextRef: default-context
